### ISSUE TITLE
AI功能问题

### ISSUE THREAD

**Issue by wzr140803-2** [lmk123/migpt-cli#16]
参数设置正常，但是日志显示429  不能正常使用，
<img width="1194" alt="1" src="https://github.com/user-attachments/assets/8130be6f-c0e7-4b4f-b6ef-74de38e467ca">
<img width="381" alt="2222" src="https://github.com/user-attachments/assets/93b88411-6f9d-4893-a309-fb62c55c2592">

**Comment by wzr140803-2** [comment]
![Uploading 333.png…]()

**Comment by lmk123** [comment]
从报错来看，你一分钟之类消耗的 token 数量超过豆包设置的限制了。

具体限制可以参考这篇文档：https://www.volcengine.com/docs/82379/1099320#%E6%A8%A1%E5%9E%8B%E6%8E%A8%E7%90%86%E9%99%90%E5%88%B6

**Comment by wzr140803-2** [comment]
![Uploading 444.png…]()

**Comment by wzr140803-2** [comment]
按说我的访问量应该不至于，刚搭建好测试 ，都没怎么使用

**Comment by wzr140803-2** [comment]
问题解决了，但是不知问题出在哪里，这个地方有两个接入点的id，换另一个就好了，但是不是我创建的，比较奇怪。
![image](https://github.com/user-attachments/assets/9584967c-75ca-482a-b9a5-e4375f228ee8)

**Comment by lmk123** [comment]
:joy: 神奇的问题
