### ISSUE TITLE
请问是否能接入本地ollama大模型？

### ISSUE THREAD

**Issue by hexart** [lmk123/migpt-cli#17]
请问是否能接入本地ollama大模型？希望能加入该功能并新增设置界面。
另，lmk123：希望能加您好友，请联系我hexart@126.com

**Comment by lmk123** [comment]
能接入的，你可以参考这篇文档：https://hcfy.app/docs/faqs/openai-compatibilty

原理是 Ollama 是提供了兼容 OpenAI 接口的调用方式的：https://github.com/ollama/ollama/blob/main/docs/openai.md

> 希望能加您好友

我可以问一下有什么特别的事情吗 :joy: 如果没有的话，通过 GitHub 或者公众号联系我即可

**Comment by hexart** [comment]
请问你公众号是多少，我有个商业项目希望合作

**Comment by lmk123** [comment]
已发送邮件到了你的邮箱，我的发信邮箱是 hi[at]hcfy.app
