### ISSUE TITLE
日志的时区似乎不正确，我尝试在环境变量中加入TZ=Asia/Shanghai；测试无改善

### ISSUE THREAD

**Issue by NJYZ-96** [lmk123/migpt-cli#18]
日志的时区似乎不正确，我尝试在环境变量中加入TZ=Asia/Shanghai；测试无改善

**Comment by lmk123** [comment]
<img width="521" alt="image" src="https://github.com/user-attachments/assets/5e8b7241-4a22-44a0-b5bc-80c70ac2d46b">

无法重现，我这边是正常的。

**Comment by NJYZ-96** [comment]
![截图_20240721094425](https://github.com/user-attachments/assets/00acb64d-66e8-46b1-8819-3658af982ccd)
我的日志时间会比实际时间早8小时；主机时间是正确的，其他容器日志时间也没问题；
我晚上重新部署试试

**Comment by Zeozzz** [comment]
同样遇到了这个问题
