### ISSUE TITLE
登录认证问题如何解决？

### ISSUE THREAD

**Issue by MaoAnmi** [lmk123/migpt-cli#19]
1、小爱音响在家庭使用（局域网环境）；
2、migpt-server在公网云服务器运行（docker部署）；
3、启动docker后提示认证报错，详细见以下日志

请问有什么好的方法吗？
![image](https://github.com/user-attachments/assets/0ad5481d-7dba-46f5-9734-39ae6c3877cb)
登录认证： 已启用
 秘密路径： 已启用
 
 
 / $$      /$$ /$$   /$$$$$$  /$$$$$$$ /$$$$$$$$$
 | $$$    /$$$|__/ /$$__  $$| $$__  $$|__  $$__/
 | $$$$  /$$$$ /$$| $$  \__/| $$  \ $$   | $$   
 | $$ $$/$$ $$| $$| $$ /$$$$| $$$$$$$/   | $$   
 | $$  $$$| $$| $$| $$|_  $$| $$____/    | $$   
 | $$\  $ | $$| $$| $$  \ $$| $$         | $$   
 | $$ \/  | $$| $$|  $$$$$$/| $$         | $$   
 |__/     |__/|__/ \______/ |__/         |__/                         
                                                                                                                  
          MiGPT v4.1.0  by: del.wang
 
 
 ❌ 小米账号登录失败 &&&START&&&{"qs":"%3Fsid%3Dmicoapi%26_json%3Dtrue%26_locale%3Dzh_CN","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"3hTMVA4oMVVESndNZC0Uemsp6u8=","sid":"micoapi","result":"error","captchaUrl":null,"callback":"https://api2.mina.mi.com/sts","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
 ❌ 小米账号登录失败 &&&START&&&{"qs":"%3Fsid%3Dxiaomiio%26_json%3Dtrue%26_locale%3Dzh_CN","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"azrnTMZJiyQ9FtUVXA7ZD76KZYM=","sid":"xiaomiio","result":"error","captchaUrl":null,"callback":"https://sts.api.io.mi.com/sts","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
 2024/07/21 00:53:08 Speaker ❌ 初始化 Mi Services 失败
 2024/07/21 00:53:08 database ❌  Error: ❌ Assertion failed
     at _LoggerManager.assert (file:///usr/local/lib/node_modules/migpt-server/node_modules/mi-gpt/dist/index.js:259:13)

**Comment by lmk123** [comment]
migpt-server 的登录认证跟你报错里的小米账号登陆失败是两回事。

小米账号登陆失败是你的小米 ID 和密码填错了，你需要再确认一下你填写的小米 ID 和密码是否正确。
