### ISSUE TITLE
AI返回回答,但是音箱不读内容，是什么原因

### ISSUE THREAD

**Issue by huxxhua** [lmk123/migpt-cli#21]
node 版本v22.5.1，本地Mac进行调试

### 控制台信息：

![CleanShot 2024-07-25 at 20 23 35@2x](https://github.com/user-attachments/assets/cdda8ae2-d1e4-4d53-a648-92402bd551ff)

### 配置内容：

![CleanShot 2024-07-25 at 20 25 27@2x](https://github.com/user-attachments/assets/ae9b49b3-0d98-467e-971c-a843c5343c6d)

麻烦大佬看看，

**Comment by lmk123** [comment]
我猜测是你型号选错了。你选择的型号是“Redmi 小爱触屏音箱 Pro 8 英寸“，但从你填写的设备 ID 看起来你使用的是不带“pro”的型号。

不过，目前兼容性列表里也确实没有不带 pro 的这个型号的播放命令 / 唤醒命令，你需要按照这个文档里的说明，自行查找一下你这个型号的这俩命令应该填写什么

**Comment by lmk123** [comment]
https://github.com/idootop/mi-gpt/blob/main/docs/compatibility.md

**Comment by lmk123** [comment]
我好像看到有人分享你这个型号的命令了。

你型号选择自定义，然后播放命令填写 [3, 1]，唤醒命令填写 [3, 2] 试试

<img width="249" alt="image" src="https://github.com/user-attachments/assets/1a15bf5e-0e20-414d-b364-39a9581a6645">

**Comment by huxxhua** [comment]
> 我好像看到有人分享你这个型号的命令了。
> 
> 你型号选择自定义，然后播放命令填写 [3, 1]，唤醒命令填写 [3, 2] 试试
> 
> <img alt="image" width="249" src="https://private-user-images.githubusercontent.com/5035625/352526182-1a15bf5e-0e20-414d-b364-39a9581a6645.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTg4MjEsIm5iZiI6MTcyMTk5ODUyMSwicGF0aCI6Ii81MDM1NjI1LzM1MjUyNjE4Mi0xYTE1YmY1ZS0wZTIwLTQxNGQtYjM2NC0zOWE5NTgxYTY2NDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjZUMTI1NTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQ2MjhiYzdiMmRhNTY5MzczYWI3MGI4ZmM0ODBmYjI2OTQ4NWNhOTQ3NDhlODg1NGRjMGRlNTQ4NDhkZDIwNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Mm2y6iAPgA7QrKbb48UIYIcP8H71QW6hZ_T8jYMDYaM">

谢谢 @lmk123 ，ttsCommand的命令不对，但是不支持连续对话遗憾
