### ISSUE TITLE
配置了百川大模型，但是启动了就退出，这个是什么问题呀

### ISSUE THREAD

**Issue by zhuxiucai** [lmk123/migpt-cli#22]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/206de499-2875-4e11-bff9-33eac5324511">

<img width="974" alt="image" src="https://github.com/user-attachments/assets/fcc26d91-34b3-4915-855e-03013c52f76e">

**Comment by lmk123** [comment]
我也不知道，我自己用的是豆包 :joy: 另外你也是第一个反馈百川的问题的人。

挂在这里等等看有没有其他人遇到过吧

**Comment by lmk123** [comment]
你第一张图里泄漏了密钥，我帮你删了图

**Comment by zhuxiucai** [comment]
> 我也不知道，我自己用的是豆包 😂 另外你也是第一个反馈百川的问题的人。
> 
> 挂在这里等等看有没有其他人遇到过吧

啊其实我用其他的api也是一样的表现。比如某些聚合api。

**Comment by zhuxiucai** [comment]
已搞定，docker配置的时候，用 network_mode: "host"

**Comment by lmk123** [comment]
👍
