### ISSUE TITLE
连得是国内能访问的chatgpt的中转地址，一直在报“啊哦，出错了，请稍后再试吧！”

### ISSUE THREAD

**Issue by firefoxgy** [lmk123/migpt-cli#28]
日志内容：
2024/10/21 11:15:50 Speaker ✅ 服务已启动...
2024/10/21 11:16:30 Speaker 🔥 现在几点了
2024/10/21 11:16:48 Speaker 🔥 请告诉我现在几点
2024/10/21 11:16:48 Speaker 🔊 让我先想想
2024/10/21 11:16:52 Speaker 🐛 {"playState":{"status":"idle","volume":20,"loop_type":1}}
2024/10/21 11:16:52 Open AI ✅ Answer:
2024/10/21 11:16:53 Speaker 🔊 啊哦，出错了，请稍后再试吧！
2024/10/21 11:16:56 Speaker 🐛 {"playState":{"status":"playing","volume":20,"loop_type":1}}
2024/10/21 11:16:57 Speaker 🐛 {"playState":{"status":"idle","volume":20,"loop_type":1}}

**Comment by lmk123** [comment]
Answer 没有文字，目测是你中转地址填错了，再确认一下
