### ISSUE TITLE
请问mi-gpt的根目录在哪呀？

### ISSUE THREAD

**Issue by ahisec** [lmk123/migpt-cli#29]
大佬，docker里mi-gpt的根目录在哪呀？目前需要将.mi.json文件放在mi-gpt的根目录，不然异地登陆过不了。

**Comment by ahisec** [comment]
找到了，将文件放在/usr/local/lib/node_modules/migpt-server/dist/下即可

**Comment by lmk123** [comment]
啊，异地登陆还跟 mijson 文件位置有关的吗
