### ISSUE TITLE
win11命令行运行npx -y migpt-server --open为什么没有反应

### ISSUE THREAD

**Issue by yun0908** [lmk123/migpt-cli#3]

**Comment by lmk123** [comment]
我试了一下，虽然有反应但确实报错了。

然后我运行 `npx migpt-server`，等 npx 安装完 migpt-server 后，再手动打开 http://localhost:36592/ 就可以了，你试试

**Comment by lmk123** [comment]
我把文档改成传统的 npm 安装的方式了，你也可以试试：https://migptgui.com/docs/intro/gui

**Comment by lmk123** [comment]
> 不用docker的话 怎么本地化部署

@xiajingjie 看这个 https://migptgui.com/docs/intro/gui

**Comment by lmk123** [comment]
由于长时间没有反馈，所以我先关闭了。如果仍有问题，可以继续留言，我会重新打开
