### ISSUE TITLE
如何禁止音箱里的小爱抢答回复

### ISSUE THREAD

**Issue by vimbackground** [lmk123/migpt-cli#32]
## 问题

进入AI以及后续的每次对话，音箱里的小爱都会抢先回复。中间AI才反应过来，开始回复。

体验很受影响，请问这种情况是否可以处理？

## 需求

单次对话或者连续对话时，小爱都保持安静，只与设置好的AI服务对话。

顺便说一下，在代码里找不到文档里说的EdgeTTS的Token的具体位置，能否提示得再具体一些：）

## 环境

本地局域网上黑群晖7.2环境上进行的docker布置，昨天拉取的最新镜像

**Comment by lmk123** [comment]
没有办法 :joy:
