### ISSUE TITLE
项目用node 启动非常费劲直接放弃

### ISSUE THREAD

**Issue by LipapaSma** [lmk123/migpt-cli#33]

**Comment by lmk123** [comment]
:joy: 爱用不用，我求着你了？还专门跑过来吐槽，真是显着你了

**Comment by LipapaSma** [comment]
玻璃心，谢谢您叻

**Comment by lmk123** [comment]
是的，我就是玻璃心。

你觉得我这个用 node 不好用，那你自己写个好用的，我一定去给你点赞评论转发三连

你要是不会写，那你就讲一讲为什么 node 费劲、你觉得改成什么样会更好，我们一起讨论怎么把这个项目变得更好。

然而事实是，你既没自己写的本事，也没人教过你怎么好好说话，那对不起，我可不惯着。

**Comment by LipapaSma** [comment]
好好好好，你说的对 ，宁别红温，别把肺气炸了，说下还回复那么多 谁惯谁 node费劲 你咋不看看你那个以来项目一顿乱放 一层层套的，本意你想开箱即用结果git一套 npm还有一套



在 2024-11-29 16:55:29，"lmk123" ***@***.***> 写道：

是的，我就是玻璃心。

你觉得我这个用 node 不好用，那你自己写个好用的，我一定去给你点赞评论转发三连

你要是不会写，那你就讲一讲为什么 node 费劲、你觉得改成什么样会更好，我们一起讨论怎么把这个项目变得更好。

然而事实是，你既没自己写的本事，也没人教过你怎么好好说话，那对不起，我可不惯着。

**Comment by lmk123** [comment]
我没红温，单纯就事论事。

> 你咋不看看你那个以来项目一顿乱放 一层层套的，本意你想开箱即用结果git一套 npm还有一套

建议你去学一下什么叫 monorepo
