### ISSUE TITLE
网络不太好只能用码云；借鉴你的思路，保持原有的node服务同时有页面可视化，也保证项目目录干净简洁

### ISSUE THREAD

**Issue by LipapaSma** [lmk123/migpt-cli#37]
https://gitee.com/lipapasma/mi-gpt-vue  网络不太好只能用码云；借鉴你的思路，保持原有的node服务同时有页面可视化，也保证项目目录干净简洁

**Comment by LipapaSma** [comment]
https://github.com/LipapaSma/mi-gpt-vue

**Comment by lmk123** [comment]
👍 原来你是有动手能力的，这比你之前跑到我这动嘴皮子强多了

我看过你的项目了，很赞！感觉你是有 UI 底子在的。这里我针对你标题里的一些观点，分享一下我个人的看法（不一定对）。

## 保持原有的node服务

我记得你之前觉得 migpt-server  不好用的原因是因为要用 node 启动，不过我看了一下你的项目也要用 node 启动，这一点似乎没有改进 #:joy: 

## 有页面可视化

这一点做的比 migpt-server 好，我现在还不支持输出 migpt 的日志，强 👍

## 保证项目目录干净简洁

单一仓库确实会更简单方便一些，无论是在开发时还是启动时。但是，随着项目进一步扩大，以下问题就会凸显出来：

### 1. 代码复用问题

比如，我将 GUI 的配置页面同时部署在了 https://migptgui.com/gui ，而这就会需要将这部分代码单独发布到 npm 里，但这样一来，如果仍然遵循“单一仓库”的做法，那么现在就会有了两个单一仓库，这会减少开发时的便捷度（比如，需要用到 `npm link` 或者在修改代码后重新手动 build npm 包）

### 2. 代码耦合问题

随着代码越来越多，单一仓库的另一个缺点就会暴露出来，即“代码耦合”。在我个人的看法中，代码应该像一个个乐高积木一样，每个部分都有自己负责的事情，然后我就可以像搭积木一样搭建成各种不同的形状。然而，如果使用单一仓库，会导致从项目已开始就没有代码分隔的概念，最后就会变成“一团浆糊”，想要重构的时候就会发现，代码就像意大利面条一样缠在一起，很难解开了。

### 我的解决方案：monorepo

这也是为什么我会在项目创建的一开始就使用 monorepo 结构的原因。表面上看，这增加了“不整洁”度或者“复杂度”，但是从长远来看，好处是大于坏处的。

## 最后

希望你能继续将你的项目维护下去，让它越来越好用！

**Comment by LipapaSma** [comment]
的确改动最小最省时间肯定还是在之前的node上改最快，你说的很有道理，共同学习。
