### ISSUE TITLE
MiGPT GUI目前是否支持数据持久化

### ISSUE THREAD

**Issue by ZACKLZ** [lmk123/migpt-cli#4]
目前看好像只能把配置导出保存，更换设备访问web界面后，配置全部没了，需要重新导入文件或是手动配置

想问下能否支持一下映射配置文件，每次web改配置保存一下，就完成配置文件修改了

**Comment by lmk123** [comment]
好的，我会在下个版本中加入

**Comment by ZACKLZ** [comment]
想问下，这是怎么保存的，毕竟没映射目录，如果下次watchtower自动更新的时候，还会在吗····

**Comment by lmk123** [comment]
我不知道 watchtower 是什么，不过配置文件位置是在 `~/.migptgui/default/migptgui.json`。

通过 docker 部署的话，这个位置确实还没加到卷中，我改下 dockerfile

**Comment by ZACKLZ** [comment]
watchtower也是个容器，可以定时检查更新部署其他容器；额外建议可以为migpt gui增加判断机制，在容器初步运行后若配置完整则直接启动

**Comment by lmk123** [comment]
> 额外建议可以为migpt gui增加判断机制，在容器初步运行后若配置完整则直接启动

#10

**Comment by lmk123** [comment]
已将 volume 的位置写进了 Dockerfile 当中 https://github.com/lmk123/migpt-cli/commit/7aabc9b9ca2ae97d43b5d693c678799803bdb637

下个版本的时候发布到 docker hub 里
