### ISSUE TITLE
TTS配置时若是使用反代域名访问，则会自动为tts局域网地址增加反代端口

### ISSUE THREAD

**Issue by ZACKLZ** [lmk123/migpt-cli#5]
我在检查日志时发现tts配置是直接取当前web域名后的端口，这样限制必须得用局域网地址下进行保存才可正确使用migpt gui的端口，若是直接配置migpt gui的web反代地址，则又会在自动在我输入的https://前再加上http:// （= =lll）
还是建议把【对外IP地址】这一栏配置放开给用户手动配吧···

另外我尝试用日志中提供的tts base地址去测试
![image](https://github.com/lmk123/migpt-cli/assets/82872715/91dcd666-e69a-4588-b0b4-fa5b1236df54)
得到上图这样的结果，也尝试后缀将tts改为/api/tts.mp3，也一样，不知道如何正确测试tts正常运行T T

**Comment by lmk123** [comment]
确实没考虑反代的情况，我默认用户应该都是直接通过跟 migpt gui 的 web 地址（也就是 http://xxx.xx.xxx:12345/ 这种形式）来使用的，所以自动把 web 地址的端口作为访问端口了。

我把现有的“对外 IP 地址”改为“对外服务地址”吧，也就是可以直接输入一个 url，你可以自定义协议、域名、端口这三个部分

**Comment by lmk123** [comment]
另外我再给 TTS 加一个测试按钮，点一下能听到声音就说明配置对了

**Comment by ZACKLZ** [comment]
感谢大佬！ @lmk123
