### ISSUE TITLE
【对外地址】的检测功能应该改为在后端检测

### ISSUE THREAD

**Issue by lmk123** [lmk123/migpt-cli#9]
目前【对外地址】的检测是从浏览器端发送请求到填写的对外地址，检测是否有响应来判断地址是否正确的。

应该改为在后端检测，原因见 https://github.com/lmk123/migpt-cli/issues/9#issuecomment-2219542946

**Comment by ZACKLZ** [comment]
目前检测按钮好像不是播放音乐，是检测链接，检测方式也有些奇怪- -，外网访问时就没法检测局域网地址，难道不是容器后端执行嘛？

**Comment by lmk123** [comment]
现有的检测只是对【对外地址】的检测，原理是在浏览器端发送了一个请求到对外地址，如果能正常响应则视为地址正确。

> 外网访问时就没法检测局域网地址

没理解，在外网部署了 `migpt-server` 之后，对外地址应该也是外网的地址才对，为什么会需要填写局域网的地址？

**Comment by ZACKLZ** [comment]
> 但现在只是对地址的响应，原理是向客户端发送请求，然后客户端将收到请求并返回结果。
> 
> > 外网访问时就没法访问其他国家
> 
> 没理解，在外网部署`migpt-server`之后，对外地址应该也是外网的地址才对，为什么需要填写集体的地址？

因为migpt和小爱音箱都在家中同一个局域网下，而我在外面，提供给音箱调用应该局域网地址更稳妥吧，起码不会受反代和ddns影响而导致失效

**Comment by lmk123** [comment]
我明白了，你不是把 migpt-server 部署在公网的云服务器上，而是在局域网里部署了，然后开了个外网访问入口。你希望的是，通过外网入口配置 migpt-server，但给小爱音箱提供局域网地址来播放语音。

这种情况确实不能直接在网页端检测。我下个版本改进一下，改成在后端检测。
